### ISSUE TITLE
Review split sequences

### ISSUE THREAD

**Issue by curiousleo** [tweag/random-quality#7]
It would be good to get a review of the implementation of the split sequences:
https://github.com/tweag/random-quality/blob/9b5651ee53d19dd722b0371e326d83e23f29326d/generate/Main.hs#L57-L115

**Comment by peteroupc** [comment]
Note that sequences SL, SR, and SA were given in section 5.6 of Schaathun.  It seems I mixed up sequences SL and SR and the first two steps of SA.  I have corrected my testing document.

**Comment by curiousleo** [comment]
Thanks! I'll take a look at the section 5.6 and your updated document.

**Comment by curiousleo** [comment]
Fixed. I think :)

**Comment by peteroupc** [comment]
One more thing: In the README, instead of saying: "splitsl, splitsr and splitsa, as described in Testing PRNGs for High-Quality Randomness", say: "... as described in section 5.6 of that paper".  Again, I didn't invent those three sequences but merely presented them in my article, and mentioned their source.
